"$schema" = 'https://starship.rs/config-schema.json'

palette = "nightfly"

[palettes.nightfly]
fern = "#87d787"
lavender = "#b0b2f4"
orange = "#f09479"
red = "#f07496"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

# [directory]
# truncation_length = 4
# truncation_symbol = "…/"
# style = "fern"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# [character]
# success_symbol = "[❯](blue)"
# error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"
# style = "bright-black"
# [git_branch]
style = "lavender"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"
#
# [cmd_duration]
# format = "[$duration]($style) "
# style = "yellow"
#
# [python]
# format = "[$virtualenv]($style) "
# style = "bright-black"
#
# [c]
# style = "green"
#
# [package]
# style = "orange"
#
# [perl]
# style = "green"
#
# [swift]
# style = "red"
#
# [terraform]
# style = "purple"
