# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"


[opener]
edit = [
  { run = 'nvim %*', block = true, desc = "nvim", for = "windows" },
  { run = 'neovide %*', orphan = true, desc = "Open with neovide", for = "windows" },
]
open = [
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
]
extract = [
  { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" },
]
play = [{ run = 'mpv --force-window %*', orphan = true, for = "windows" }]
