general:
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: 'window_focus' # Options: 'monitor_focus', 'window_focus'

gaps:
  scale_with_dpi: true
  inner_gap: '4px'
  outer_gap:
    top: '44px'
    right: '4px'
    bottom: '4px'
    left: '4px'

window_effects:
  focused_window:
    border:
      enabled: true
      # color: '#8dbcff'
      # color: '#21c7a8'
      color: '#82aaff'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square' # Options: 'square', 'rounded', 'small_rounded'
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: 'social'
    display_name: 'Social'
  - name: 'browser'
    display_name: 'Browser'
  - name: 'code'
    display_name: 'Code'
  - name: 'notes'
    display_name: 'Notes'
  - name: 'terminal'
    display_name: 'Windows Terminal'
  - name: 'explorer'
    display_name: 'Explorer'
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  # social
  - commands: ['move --workspace social', 'focus --workspace social']
    match:
      - window_process: { equals: 'Discord' }
      - window_process: { equals: 'ts3client_win64' }

  # browser
  - commands: ['move --workspace browser', 'focus --workspace browser']
    match:
      - window_process: { equals: 'msedge|brave|chrome' }

  # terminal
  - commands: ['move --workspace terminal', 'focus --workspace terminal']
    match:
      - window_process: { equals: 'WindowsTerminal' }

  # explorer
  - commands: ['move --workspace explorer', 'focus --workspace explorer']
    match:
      - window_process: { equals: 'explorer' }

  # Ignore
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: {equals: 'Ueli'}

binding_modes:
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Workspaces

  # social
  - commands: ['focus --workspace social']
    bindings: ['alt+s']
  - commands: ['move --workspace social', 'focus --workspace social']
    bindings: ['alt+shift+s']

  # browser
  - commands: ['focus --workspace browser']
    bindings: ['alt+b']
  - commands: ['move --workspace browser', 'focus --workspace browser']
    bindings: ['alt+shift+b']

  # browser
  - commands: ['focus --workspace code']
    bindings: ['alt+c']
  - commands: ['move --workspace code', 'focus --workspace code']
    bindings: ['alt+shift+c']

  # terminal
  - commands: ['focus --workspace terminal']
    bindings: ['alt+w']
  - commands: ['move --workspace terminal', 'focus --workspace terminal']
    bindings: ['alt+shift+w']

  # explorer
  - commands: ['focus --workspace explorer']
    bindings: ['alt+e']
  - commands: ['move --workspace explorer', 'focus --workspace explorer']
    bindings: ['alt+shift+e']

  # notes
  - commands: ['focus --workspace notes']
    bindings: ['alt+n']
  - commands: ['move --workspace notes', 'focus --workspace notes']
    bindings: ['alt+shift+n']

  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']

  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']

  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']

  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']

  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']

  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']

  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']

  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']

  - commands: ['focus --workspace 9']
    bindings: ['alt+9']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']


  # Focus
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # Move window
  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  # Move workspace
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+down']

  # Resize
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']
  - commands: ['toggle-tiling']
    bindings: ['alt+t']
  - commands: ['toggle-fullscreen']
    bindings: ['alt+x']
  - commands: ['toggle-minimized']
    bindings: ['alt+m']
  - commands: ['close']
    bindings: ['alt+shift+q']

  - commands: ['wm-exit']
    bindings: ['alt+shift+z']
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']
  - commands: ['wm-redraw']
    bindings: ['alt+r']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ['shell-exec cmd']
  #   bindings: ['alt+enter']

  - commands: ['focus --next-workspace']
    bindings: ['alt+right']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+left']

  - commands: ['focus --recent-workspace']
    bindings: ['alt+back']

