---
general:
  startup_commands: [shell-exec zebar]
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  show_all_in_taskbar: false
  cursor_jump:
    enabled: true
    trigger: window_focus
gaps:
  inner_gap: 8px
  outer_gap:
    top: 44px
    right: 4px
    bottom: 4px
    left: 4px
window_effects:
  focused_window:
    border:
      enabled: true
      color: '#8dbcff'
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
window_behavior:
  initial_state: tiling
  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: false
      shown_on_top: false
workspaces:
  - name: browser
    display_name: Browser
    bind_to_monitor: 0
  - name: c
    display_name: Code
    bind_to_monitor: 0
  - name: v
    display_name: Virtual Scratchpad
    bind_to_monitor: 0
  - name: d
    display_name: Demo
    bind_to_monitor: 0
  - name: a
    display_name: AutoCAD
    bind_to_monitor: 0
  - name: n
    display_name: Notes
    bind_to_monitor: 0
  - name: w
    display_name: Windows Terminal
    bind_to_monitor: 0
  - name: '1'
    display_name: '1'
    bind_to_monitor: 0
  - name: '2'
    display_name: '2'
    bind_to_monitor: 0
  - name: '3'
    display_name: '3'
    bind_to_monitor: 0
  - name: '4'
    display_name: '4'
    bind_to_monitor: 0
  - name: '5'
    display_name: '5'
    bind_to_monitor: 0
  - name: e
    display_name: Explorer
    bind_to_monitor: 1
  - name: gitbutler
    display_name: GitButler
    bind_to_monitor: 0
  - name: gitkraken
    display_name: GitKraken
    bind_to_monitor: 0
  - name: '6'
    display_name: '6'
    bind_to_monitor: 1
  - name: '7'
    display_name: '7'
    bind_to_monitor: 1
  - name: '8'
    display_name: '8'
    bind_to_monitor: 1
  - name: '9'
    display_name: '9'
    bind_to_monitor: 1
  # - name: "0"
  #   display_name: "0"
  #   bind_to_monitor: 1
  - name: s
    display_name: Social
    bind_to_monitor: 1
  # - name: "o"
  #   display_name: "Output"
  #   bind_to_monitor: 1
window_rules:
  # IGNORE
  - commands: [ignore]
    match:
      - window_process: {equals: zebar}
      - window_title: {regex: '[Pp]icture.in.[Pp]icture'}
        window_class: {regex: Chrome_WidgetWin_1|MozillaDialogClass}
      - window_process: {equals: PowerToys.PowerAccent}
      - window_process: {equals: PowerToys.MeasureTool}
      - window_process: {equals: Lively}
        window_class: {regex: HwndWrapper*}
      - window_process: {equals: ueli}

  # Autocad
  - commands: [move --workspace a]
    match:
      - window_process: {equals: acad}

  # Screenshots
  - commands: [set-floating --shown-on-top]
    match:
      - window_process: {equals: ShareX}

        # Excel Find and Replace
  - commands: [set-floating]
    match:
      - window_title: {equals: Find and Replace}

  # LINQPad
  - commands: [move --workspace v, focus --workspace v]
    match:
      - window_title: {regex: LINQPad \d}

  # Visual Studio
  - commands: [set-floating]
    match:
      - window_process: {equals: devenv}
        # window_title: { regex: '^((?!output).)*$' }

  # Visual Studio
  - commands: [move --workspace c, focus --workspace c, set-tiling]
    match:
      - window_title: {regex: .*Microsoft Visual Studio Preview.*}

  # Visual Studio Code
  - commands: [move --workspace c, focus --workspace c, set-tiling]
    match:
      - window_process: {equals: Code}

  # - commands:
  #     ["move --workspace 1", "focus --workspace 1", "set-tiling", "wm-redraw"]
  #   match:
  #     - window_title: { equals: "Output" }

      # TODO: How to get the output window to change workspace?
  # - commands: ["move --workspace 6", "focus --workspace 6", 'set-tiling']
  #   match:
  #     - window_title: { regex: 'Output' }

  # Floating
  - commands: [set-floating]
    match:
      - window_title: {equals: Search}
      - window_title: {equals: Search everywhere}
      - window_title: {equals: Find all}

  # ESI Terminals
  - commands: [move --workspace d]
    match:
      - window_title: {regex: ESI AutoMation}
  - commands: [set-floating --centered]
    match:
      - window_process: {equals: ESI-Term-Dev}
      - window_process: {equals: ESI-Term}

  # Git
  - commands: [move --workspace gitbutler, focus --workspace gitbutler]
    match:
      - window_title: {equals: GitButler}
      - window_process: {equals: sublime_merge}
  - commands: [move --workspace gitkraken, focus --workspace gitkraken]
    match:
      - window_process: {equals: gitkraken}

  # File Explorer
  - commands: [move --workspace e, focus --workspace e]
    match:
      - window_process: {equals: explorer}
      - window_process: {equals: FPilot}

  # Social
  - commands: [move --workspace s, focus --workspace s]
    match:
      - window_process: {equals: olk}
      - window_process: {equals: ms-teams}

  # Web Browsers (brave, vivaldi, zen)
  - commands: [move --workspace browser, focus --workspace browser]
    match:
      - window_process: {equals: thorium}
      - window_process: {equals: vivaldi}
      - window_process: {equals: brave}
      - window_process: {equals: zen}

  # Windows Terminal
  # - commands: [set-floating --x-pos 0 --y-pos 0 --width 2880 --height 2050]
  # - commands: [set-floating ]
  # - commands: ["set-fullscreen"]
  - commands: [move --workspace w, focus --workspace w]
    match:
      - window_process: {equals: WindowsTerminal}

  # Obsidian
  - commands: [move --workspace n, focus --workspace n]
    match:
      - window_process: {equals: Obsidian}

        # TODO: Reenable autocad automove workspace
  # Autocad
  # - commands: ["move --workspace a", "focus --workspace a"]
  #   match:
  #     - window_process: { equals: "acad" }
binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: resize
    keybindings:
      - commands: [resize --width -2%]
        bindings: [h, left]
      - commands: [resize --width +2%]
        bindings: [l, right]
      - commands: [resize --height +2%]
        bindings: [k, up]
      - commands: [resize --height -2%]
        bindings: [j, down]
      # Press enter/escape to return to default keybindings.
      - commands: [wm-disable-binding-mode --name resize]
        bindings: [escape, enter]

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: pause
    keybindings:
      - commands: [wm-disable-binding-mode --name pause]
        bindings: [alt+shift+p]
keybindings:
  # Shift focus in a given direction.
  - commands: [focus --direction left]
    bindings: [alt+h]
  - commands: [focus --direction right]
    bindings: [alt+l]
  - commands: [focus --direction up]
    bindings: [alt+k]
  - commands: [focus --direction down]
    bindings: [alt+j]

  # Move focused window in a given direction.
  - commands: [move --direction left]
    bindings: [alt+shift+h, alt+shift+left]
  - commands: [move --direction right]
    bindings: [alt+shift+l, alt+shift+right]
  - commands: [move --direction up]
    bindings: [alt+shift+k, alt+shift+up]
  - commands: [move --direction down]
    bindings: [alt+shift+j, alt+shift+down]

  # Resize focused window by a percentage or pixel amount.
  - commands: [resize --width -2%]
    bindings: [alt+u]
  - commands: [resize --width +2%]
    bindings: [alt+p]
  - commands: [resize --height +2%]
    bindings: [alt+o]
  - commands: [resize --height -2%]
    bindings: [alt+i]

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  #  - commands: ['wm-enable-binding-mode --name resize']
  #  bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: [wm-enable-binding-mode --name pause]
    bindings: [alt+shift+p]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: [toggle-tiling-direction]
    bindings: [alt+q]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: [wm-cycle-focus]
    bindings: [alt+space]

  # Change the focused window to be floating.
  - commands: [toggle-floating --centered]
    bindings: [alt+shift+space]

  # Change the focused window to be tiling.
  - commands: [toggle-tiling]
    bindings: [alt+t]

  # Change the focused window to be fullscreen.
  - commands: [toggle-fullscreen]
    bindings: [alt+x]

  # Minimize focused window.
  - commands: [toggle-minimized]
    bindings: [alt+m]

  # Close focused window.
  - commands: [close]
    bindings: [alt+shift+q]

  # Kill GlazeWM process safely.
  - commands: [wm-exit]
    bindings: [alt+shift+x]

  # Re-evaluate configuration file.
  - commands: [wm-reload-config]
    bindings: [alt+shift+r]

  # Redraw all windows.
  - commands: [wm-redraw]
    bindings: [alt+r]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ['shell-exec ueli']
  # - commands: ['shell-exec wt']
  #   bindings: ['alt+shift+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: [focus --next-workspace]
    bindings: [alt+right]
  - commands: [focus --prev-workspace]
    bindings: [alt+left]
  # - commands: ['focus --next-workspace']
  #   bindings: ['alt+f']
  # - commands: ['focus --prev-workspace']
  #   bindings: ['alt+s']
  # Focus the workspace that last had focus.
  - commands: [focus --recent-workspace]
    bindings: [alt+back]
    # bindings: ['alt+q']

  # Change focus to a workspace defined in `workspaces` config.
    #
  - commands: [focus --workspace d]
    bindings: [alt+d]
  - commands: [move --workspace d, focus --workspace d]
    bindings: [alt+shift+d]

    #
  - commands: [focus --workspace a]
    bindings: [alt+a]
  - commands: [move --workspace a, focus --workspace a]
    bindings: [alt+shift+a]

    #
  - commands: [focus --workspace n]
    bindings: [alt+n]
  - commands: [move --workspace n, focus --workspace n]
    bindings: [alt+shift+n]

    #
  - commands: [focus --workspace s]
    bindings: [alt+s]
  - commands: [move --workspace s, focus --workspace s]
    bindings: [alt+shift+s]

    # Browser
  - commands: [focus --workspace browser]
    bindings: [alt+b]
  - commands: [move --workspace browser, focus --workspace browser]
    bindings: [alt+shift+b]

    #
  - commands: [focus --workspace c]
    bindings: [alt+c]
  - commands: [move --workspace c, focus --workspace c]
    bindings: [alt+shift+c]

    #
  - commands: [focus --workspace v]
    bindings: [alt+v]
  - commands: [move --workspace v, focus --workspace v]
    bindings: [alt+shift+v]

    #
  - commands: [focus --workspace e]
    bindings: [alt+e]
  - commands: [move --workspace e, focus --workspace e]
    bindings: [alt+shift+e]

    #
  - commands: [focus --workspace gitbutler]
    bindings: [alt+g]
  - commands: [move --workspace gitbutler, focus --workspace gitbutler]
    bindings: [alt+shift+g]

    #
  - commands: [focus --workspace gitkraken]
    bindings: [control+alt+g]
  - commands: [move --workspace gitkraken, focus --workspace gitkraken]
    bindings: [control+alt+shift+g]

    #
  - commands: [focus --workspace w]
    bindings: [alt+w]
  - commands: [move --workspace w, focus --workspace w]
    bindings: [alt+shift+w]

    #
  - commands: [focus --workspace 1]
    bindings: [alt+1]
  - commands: [move --workspace 1, focus --workspace 1]
    bindings: [alt+shift+1]

    #
  - commands: [focus --workspace 2]
    bindings: [alt+2]
  - commands: [move --workspace 2, focus --workspace 2]
    bindings: [alt+shift+2]

    #
  - commands: [focus --workspace 3]
    bindings: [alt+3]
  - commands: [move --workspace 3, focus --workspace 3]
    bindings: [alt+shift+3]

    #
  - commands: [focus --workspace 4]
    bindings: [alt+4]
  - commands: [move --workspace 4, focus --workspace 4]
    bindings: [alt+shift+4]

    #
  - commands: [focus --workspace 5]
    bindings: [alt+5]
  - commands: [move --workspace 5, focus --workspace 5]
    bindings: [alt+shift+5]
  # - commands: ["focus --workspace o"]
  #   bindings: ["alt+o"]
    #
  - commands: [focus --workspace 6]
    bindings: [alt+6]
  - commands: [move --workspace 6, focus --workspace 6]
    bindings: [alt+shift+6]
    #
  - commands: [focus --workspace 7]
    bindings: [alt+7]
  - commands: [move --workspace 7, focus --workspace 7]
    bindings: [alt+shift+7]
  - commands: [focus --workspace 8]
    bindings: [alt+8]
  - commands: [move --workspace 8, focus --workspace 8]
    bindings: [alt+shift+8]
  - commands: [focus --workspace 9]
    bindings: [alt+9]
  - commands: [move --workspace 9, focus --workspace 9]
    bindings: [alt+shift+9]
  - commands: [focus --workspace 0]
    bindings: [alt+0]
  - commands: [move --workspace 0, focus --workspace 0]
    bindings: [alt+shift+0]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: [move-workspace --direction left]
    bindings: [alt+shift+left]
  - commands: [move-workspace --direction right]
    bindings: [alt+shift+right]
  - commands: [move-workspace --direction up]
    bindings: [alt+shift+up]
  - commands: [move-workspace --direction down]
    bindings: [alt+shift+down]
