fork = false
frame = "full"
idle = false
maximized = false
# mouse-cursor-icon = "arrow"
# no-multigrid = false
# srgb = false
# tabs = true
theme = "auto"
# title-hidden = true
vsync = false
wsl = false

[font]
normal = [
  "CommitMono Nerd Font",
] # Will use the bundled Fira Code Nerd Font by default
size = 16.0
